# Generated by Django 2.2 on 2019-09-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190927_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': (('test', 'test111'), ('test2', 'test222')), 'verbose_name': '员工', 'verbose_name_plural': '员工管理'},
        ),
    ]
