# Generated by Django 2.2 on 2019-09-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190927_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': (('test', 'test111'), ('test2', 'test222'), ('Simpleui', 'view_simpleui')), 'verbose_name': '员工', 'verbose_name_plural': '员工管理'},
        ),
    ]
