# Generated by Django 2.2 on 2019-10-27 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0004_auto_20190927_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': (('test', 'test111'), ('test2', 'test222'), ('Simpleui', 'simpleui')), 'verbose_name': '员工', 'verbose_name_plural': '员工管理'},
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('type', models.IntegerField(choices=[(1, '采购商'), (2, '供应商'), (3, '采购&供应')], verbose_name='客户类别')),
                ('name', models.CharField(default='选填', max_length=100, verbose_name='公司名称')),
                ('lite_name', models.CharField(help_text='如无公司则填联系人或CEO名称', max_length=20, primary_key=True, serialize=False, verbose_name='公司简称')),
                ('address', models.CharField(default='选填', max_length=200, verbose_name='公司地址')),
                ('phone', models.CharField(default='选填', max_length=40, verbose_name='公司电话')),
                ('website', models.URLField(default='example.com', verbose_name='网址')),
                ('business', models.CharField(max_length=64, verbose_name='主营业务')),
                ('ceo', models.CharField(default='选填', max_length=50, verbose_name='CEO')),
                ('email', models.EmailField(default='example@email.com', max_length=100, verbose_name='CEO邮箱')),
                ('ceo_phone', models.CharField(default='选填', max_length=20, verbose_name='CEO电话')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_email', models.EmailField(max_length=100, verbose_name='联系人邮箱')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='联系人电话')),
                ('status', models.IntegerField(choices=[(1, '合作'), (2, '终止'), (3, '开发')], verbose_name='合作状态')),
                ('line_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='信用额度')),
                ('input_time', models.DateField(default=datetime.datetime.now, verbose_name='添加日期')),
                ('text', models.CharField(default='选填', max_length=480, verbose_name='备注')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='业务')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
