# Generated by Django 3.0 on 2020-01-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_employe_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='avatar',
            field=models.ImageField(help_text='员工的照片，在列表会默认显示为图片', null=True, upload_to='', verbose_name='照片'),
        ),
    ]
