# Generated by Django 3.0 on 2020-01-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200114_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='avatar',
            new_name='avatar_img',
        ),
    ]
