# Generated by Django 3.1 on 2020-08-19 14:24

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20200819_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo3',
            options={'ordering': ('pk',), 'permissions': (('batchSettings', '批量设置'),), 'verbose_name': 'demo2', 'verbose_name_plural': 'demo2'},
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='demo1_ptr',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f19',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f20',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f21',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f22',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f23',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f24',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f25',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f26',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f27',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f28',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f29',
        ),
        migrations.RemoveField(
            model_name='demo3',
            name='f30',
        ),
        migrations.AlterField(
            model_name='demo3',
            name='f1',
            field=models.CharField(default=demo.models.get_id, max_length=32, primary_key=True, serialize=False),
        ),
    ]
