# Generated by Django 3.1 on 2020-08-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20200819_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo3',
            options={'ordering': ('pk',), 'permissions': (('batchSettings', '批量设置'),), 'verbose_name': 'demo3', 'verbose_name_plural': 'demo3'},
        ),
    ]
