# Generated by Django 3.1 on 2020-08-26 10:14

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_auto_20200819_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='images',
            field=simplepro.components.fields.ManyToManyField(blank=True, to='demo.Image', verbose_name='照片列表'),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=simplepro.components.fields.CharField(db_index=True, help_text='一个部门的名字应该唯一', max_length=128, unique=True, verbose_name='部门名'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='avatar_img',
            field=simplepro.components.fields.ImageField(help_text='员工的照片，在列表会默认显示为图片', max_length=256, null=True, verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='birthday',
            field=simplepro.components.fields.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='create_time',
            field=simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='department',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='enable',
            field=simplepro.components.fields.SwitchField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=simplepro.components.fields.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='idCard',
            field=simplepro.components.fields.CharField(blank=True, help_text='18位的身份证号码', max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=simplepro.components.fields.CharField(db_index=True, help_text='员工的名字', max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=simplepro.components.fields.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='time',
            field=simplepro.components.fields.TimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='title',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title', verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='update_time',
            field=simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
