# Generated by Django 3.1 on 2020-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_remove_employe_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', '优'), ('B', '良'), ('C', '中'), ('D', '差')], max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('score', models.ManyToManyField(null=True, to='demo.ScoreModel', verbose_name='分数')),
            ],
            options={
                'verbose_name': '多对多测试',
                'verbose_name_plural': '多对多测试',
            },
        ),
    ]
