# Generated by Django 3.1 on 2020-12-03 11:47

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_auto_20200826_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_name', models.UUIDField(blank=True, null=True, verbose_name='创建人ID')),
                ('client_id', models.CharField(default='1', max_length=100, verbose_name='ClientId')),
                ('client_secret', models.CharField(default='1', max_length=100, verbose_name='ClientSecret')),
                ('user', models.UUIDField(blank=True, null=True, verbose_name='用户ID')),
                ('deleted', simplepro.components.fields.SwitchField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_name', models.UUIDField(blank=True, null=True, verbose_name='创建人ID')),
                ('client_id', models.CharField(default='1', max_length=100, verbose_name='ClientId')),
                ('client_secret', models.CharField(default='1', max_length=100, verbose_name='ClientSecret')),
                ('user', models.UUIDField(blank=True, null=True, verbose_name='用户ID')),
                ('deleted', simplepro.components.fields.SwitchField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('desc', simplepro.editor.fields.UETextField(blank=True, null=True, verbose_name='商品详情')),
                ('hot', simplepro.components.fields.SwitchField(default=False, verbose_name='热门')),
                ('category', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.productcategory', verbose_name='商品品类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
