# Generated by Django 3.1.7 on 2021-07-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_product_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段1')),
                ('name2', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段2')),
                ('name3', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段3')),
                ('name4', models.CharField(blank=True, max_length=128, null=True, verbose_name='字段4')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title')),
            ],
        ),
        migrations.RemoveField(
            model_name='expertcomment',
            name='expert',
        ),
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='ExpertComment',
        ),
    ]
