# Generated by Django 3.1.7 on 2021-07-21 06:19

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0024_auto_20210721_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinfo',
            name='name5',
            field=simplepro.components.fields.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='extinfo',
            name='name6',
            field=simplepro.components.fields.DateTimeField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='extinfo',
            name='name7',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department'),
        ),
        migrations.AddField(
            model_name='extinfo',
            name='name8',
            field=simplepro.components.fields.SwitchField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='extinfo',
            name='name1',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='字段1'),
        ),
        migrations.AlterField(
            model_name='extinfo',
            name='name2',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='字段2'),
        ),
        migrations.AlterField(
            model_name='extinfo',
            name='name3',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='字段3'),
        ),
        migrations.AlterField(
            model_name='extinfo',
            name='name4',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='字段4'),
        ),
        migrations.AlterField(
            model_name='extinfo',
            name='title',
            field=simplepro.components.fields.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title'),
        ),
    ]
