# Generated by Django 3.2.6 on 2021-08-18 12:33

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_auto_20210816_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Native',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '原生页面',
                'verbose_name_plural': '原生页面',
            },
        ),
    ]
