# Generated by Django 3.2.8 on 2021-10-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_auto_20210820_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
    ]
