# Generated by Django 3.2.9 on 2021-11-29 08:13

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_alter_productcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_name', models.UUIDField(blank=True, null=True, verbose_name='创建人ID')),
                ('client_id', models.CharField(default='1', max_length=100, verbose_name='ClientId')),
                ('client_secret', models.CharField(default='1', max_length=100, verbose_name='ClientSecret')),
                ('user', models.UUIDField(blank=True, null=True, verbose_name='用户ID')),
                ('deleted', simplepro.components.fields.SwitchField(default=False, verbose_name='删除标记')),
                ('num', simplepro.components.fields.IntegerField(verbose_name='数字')),
                ('name', simplepro.components.fields.CharField(max_length=64, verbose_name='标签名')),
                ('product', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
            },
        ),
    ]
