# Generated by Django 4.0.2 on 2022-05-25 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0030_producttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(default='', max_length=50, verbose_name='供应商名称')),
                ('add', simplepro.components.fields.CharField(blank=True, default='', max_length=100, null=True, verbose_name='供应商地址')),
                ('contact', simplepro.components.fields.CharField(default='', max_length=10, verbose_name='联系人')),
                ('phone', simplepro.components.fields.CharField(default='', max_length=20, unique=True, verbose_name='联系人电话')),
                ('isComp', simplepro.components.fields.RadioField(choices=[(1, '对公账户'), (0, '非对公账户')], default=0, verbose_name='属性')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '供应商管理',
                'verbose_name_plural': '供应商管理',
            },
        ),
    ]
