# Generated by Django 4.1.3 on 2022-11-29 08:44

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_supplierinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', simplepro.components.fields.CharField(blank=True, max_length=16, null=True, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': 'API分组',
                'verbose_name_plural': 'API分组',
            },
        ),
        migrations.CreateModel(
            name='ApiList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', simplepro.components.fields.CharField(blank=True, max_length=16, null=True, verbose_name='分组名称')),
                ('group', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.apigroup', verbose_name='所厲分组')),
            ],
            options={
                'verbose_name': 'API列表',
                'verbose_name_plural': 'API列表',
            },
        ),
    ]
