# Generated by Django 4.1.3 on 2022-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_apigroup_apilist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='分数')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '区间搜索',
                'verbose_name_plural': '区间搜索',
            },
        ),
    ]
