# Generated by Django 4.0.2 on 2022-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='名称'),
        ),
    ]
