# Generated by Django 4.0.2 on 2022-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '对话框',
                'verbose_name_plural': '对话框',
            },
        ),
    ]
