# Generated by Django 3.1 on 2020-08-22 10:41

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200822_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.ImageField(max_length=256, verbose_name='图片上传')),
            ],
            options={
                'verbose_name': 'Image图片上传',
                'verbose_name_plural': 'Image图片上传',
            },
        ),
    ]
