# Generated by Django 3.1 on 2020-08-24 01:56

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20200822_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.RateField(verbose_name='评分1')),
                ('f2', simplepro.components.fields.RateField(verbose_name='评分2')),
            ],
            options={
                'verbose_name': 'Rate评分',
                'verbose_name_plural': 'Rate评分',
            },
        ),
    ]
