# Generated by Django 3.1 on 2020-08-24 07:39

from django.db import migrations
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_timemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemodel',
            name='f3',
            field=simplepro.components.fields.TimeField(default=django.utils.timezone.now, verbose_name='Time时间选择2'),
        ),
    ]
