# Generated by Django 3.1 on 2020-08-24 07:48

from django.db import migrations, models
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_timemodel_f3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.TimeField(verbose_name='Date日期选择1')),
                ('f2', simplepro.components.fields.TimeField(default=django.utils.timezone.now, help_text='不可清除', verbose_name='Date日期选择2')),
                ('f3', simplepro.components.fields.TimeField(default=django.utils.timezone.now, help_text='不可编辑', verbose_name='Date日期选择3')),
            ],
            options={
                'verbose_name': 'Date日期选择',
                'verbose_name_plural': 'Date日期选择',
            },
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='f2',
            field=simplepro.components.fields.TimeField(default=django.utils.timezone.now, help_text='不可清除', verbose_name='Time时间选择2'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='f3',
            field=simplepro.components.fields.TimeField(default=django.utils.timezone.now, help_text='不可编辑', verbose_name='Time时间选择3'),
        ),
    ]
