# Generated by Django 3.1 on 2020-08-24 07:51

from django.db import migrations
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20200824_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datemodel',
            name='f1',
            field=simplepro.components.fields.DateField(verbose_name='Date日期选择1'),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='f2',
            field=simplepro.components.fields.DateField(default=django.utils.timezone.now, help_text='不可清除', verbose_name='Date日期选择2'),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='f3',
            field=simplepro.components.fields.DateField(default=django.utils.timezone.now, editable=False, help_text='不可编辑', verbose_name='Date日期选择3'),
        ),
    ]
