# Generated by Django 3.1 on 2020-08-24 07:56

from django.db import migrations, models
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_auto_20200824_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.DateTimeField(verbose_name='DateTime日期时间1')),
                ('f2', simplepro.components.fields.DateTimeField(default=django.utils.timezone.now, help_text='不可清除', verbose_name='DateTime日期时间2')),
                ('f3', simplepro.components.fields.DateTimeField(default=django.utils.timezone.now, help_text='不可编辑', verbose_name='DateTime日期时间3')),
            ],
            options={
                'verbose_name': 'DateTime日期时间',
                'verbose_name_plural': 'DateTime日期时间',
            },
        ),
    ]
