# Generated by Django 3.1 on 2020-08-24 10:10

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_charmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='charmodel',
            name='f7',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='复合输入框'),
        ),
        migrations.AddField(
            model_name='charmodel',
            name='f8',
            field=simplepro.components.fields.CharField(blank=True, max_length=128, null=True, verbose_name='复合输入框'),
        ),
        migrations.AlterField(
            model_name='charmodel',
            name='f2',
            field=simplepro.components.fields.CharField(max_length=128, verbose_name='多行输入'),
        ),
        migrations.AlterField(
            model_name='charmodel',
            name='f3',
            field=simplepro.components.fields.CharField(max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='charmodel',
            name='f4',
            field=simplepro.components.fields.CharField(max_length=128, verbose_name='左边带图标'),
        ),
        migrations.AlterField(
            model_name='charmodel',
            name='f5',
            field=simplepro.components.fields.CharField(max_length=128, verbose_name='右边带图标'),
        ),
        migrations.AlterField(
            model_name='charmodel',
            name='f6',
            field=simplepro.components.fields.CharField(max_length=128, verbose_name='显示可输入长度'),
        ),
    ]
