# Generated by Django 3.1 on 2020-08-24 10:15

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20200824_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='f2',
            field=simplepro.components.fields.ImageField(blank=True, help_text='指定上传地址为/123，模拟出错', max_length=128, null=True, verbose_name='图片上传'),
        ),
    ]
