# Generated by Django 3.1 on 2020-08-26 03:22

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_auto_20200826_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='one_to_many',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='many_to_many',
            field=simplepro.components.fields.ManyToManyField(blank=True, to='components.StudentManyToManyModel', verbose_name='多对多字段'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='one_to_one',
            field=simplepro.components.fields.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.studentonetoonemodel', verbose_name='一对一字段'),
        ),
    ]
