# Generated by Django 3.1 on 2020-08-26 08:33

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_auto_20200826_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='地区')),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='area',
            field=simplepro.components.fields.ForeignKey(blank=True, help_text='一对多', null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.studentarea', verbose_name='地区'),
        ),
    ]
