# Generated by Django 3.1 on 2020-08-26 10:14

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0021_auto_20200826_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='school',
            field=simplepro.components.fields.IntegerField(choices=[(0, '北大'), (1, '清华'), (2, '复旦'), (3, '交大'), (4, '厦大'), (5, '深大'), (6, '中山大学'), (7, '东南大学'), (8, '南开大学')], default=0, verbose_name='学校'),
        ),
    ]
