# Generated by Django 3.1 on 2020-08-26 14:24

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_auto_20200826_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=32, verbose_name='穿梭框多对多')),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='transfer',
            field=simplepro.components.fields.TransferField(blank=True, help_text='基于many_to_many字段', to='components.StudentTransferModel', verbose_name='穿梭框'),
        ),
    ]
