# Generated by Django 3.1 on 2020-08-26 14:28

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_auto_20200826_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='transfer',
        ),
        migrations.RenameModel(
            old_name='StudentTransferModel',
            new_name='TransferManyToManyModel',
        ),
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名字')),
                ('transfer', simplepro.components.fields.TransferField(blank=True, help_text='基于many_to_many字段', to='components.TransferManyToManyModel', verbose_name='穿梭框')),
            ],
            options={
                'verbose_name': 'Transfer 穿梭框',
                'verbose_name_plural': 'Transfer 穿梭框',
            },
        ),
    ]
