# Generated by Django 3.1 on 2020-08-27 03:55

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_auto_20200826_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='one_to_one',
        ),
        migrations.CreateModel(
            name='OneToOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(default='张三', max_length=128, verbose_name='名字')),
                ('one_to_one', simplepro.components.fields.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.studentonetoonemodel', verbose_name='一对一字段')),
            ],
            options={
                'verbose_name': '一对一 Select',
                'verbose_name_plural': '一对一 Select',
            },
        ),
    ]
