# Generated by Django 3.1 on 2020-12-03 03:45

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_uuidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuidmodel',
            name='name',
            field=simplepro.components.fields.CharField(default=11, max_length=32, verbose_name='名字'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uuidmodel',
            name='uid',
            field=models.UUIDField(default='ac51afe9bb8c4234b6441b1ee33192c9', editable=False, verbose_name='uuid'),
        ),
    ]
