# Generated by Django 3.1 on 2020-12-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0030_auto_20201203_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuidmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='uuidmodel',
            name='uid',
            field=models.UUIDField(default='b60b24397a724b79a93b56215bbe0bc2', editable=False, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
    ]
