# Generated by Django 3.1 on 2020-12-03 03:49

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0031_auto_20201203_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDKeyModel',
            fields=[
                ('uid', models.UUIDField(default='443f32d11fa0465d97e2ad043c4cc4c4', editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名字')),
            ],
            options={
                'verbose_name': 'UUID支持',
                'verbose_name_plural': 'UUID支持',
            },
        ),
        migrations.DeleteModel(
            name='UUIDModel',
        ),
    ]
