# Generated by Django 3.1 on 2020-12-03 11:47

import components.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0033_auto_20201203_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidkeymodel',
            name='uid',
            field=models.UUIDField(default=components.models.get_uuid, editable=False, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
    ]
