# Generated by Django 3.2.6 on 2021-08-18 12:15

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0036_meditormodel_md2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxmodeltest',
            name='f',
            field=simplepro.components.fields.CheckboxField(blank=True, default=None, help_text='继承自CharField，逗号分隔', max_length=128, null=True, verbose_name='复选框'),
        ),
    ]
