# Generated by Django 3.2.8 on 2021-10-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0039_auto_20210819_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证')),
            ],
        ),
        migrations.AddField(
            model_name='studentonetoonemodel',
            name='id_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.studentidcard'),
        ),
    ]
