# Generated by Django 4.0.2 on 2022-03-13 14:09

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0042_meditormodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='desc',
            field=simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='layer',
            name='status',
            field=models.IntegerField(choices=[(0, '默认'), (1, '其他')], default=0, max_length=32, verbose_name='状态'),
        ),
    ]
