# Generated by Django 4.0.5 on 2022-07-28 04:04

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0045_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputnumbermodel',
            name='f2',
            field=simplepro.components.fields.InputNumberField(default=1, help_text='继承自IntegerField', verbose_name='InputNumber计数器'),
        ),
        migrations.AddField(
            model_name='inputnumbermodel',
            name='f3',
            field=simplepro.components.fields.InputNumberField(default=1, help_text='继承自IntegerField', verbose_name='InputNumber计数器'),
        ),
        migrations.AddField(
            model_name='inputnumbermodel',
            name='f4',
            field=simplepro.components.fields.InputNumberField(default=1, help_text='继承自IntegerField', verbose_name='InputNumber计数器'),
        ),
        migrations.AddField(
            model_name='inputnumbermodel',
            name='f5',
            field=simplepro.components.fields.InputNumberField(default=1, help_text='继承自IntegerField', verbose_name='InputNumber计数器'),
        ),
        migrations.AddField(
            model_name='inputnumbermodel',
            name='f6',
            field=simplepro.components.fields.InputNumberField(default=1, help_text='继承自IntegerField', verbose_name='InputNumber计数器'),
        ),
    ]
