# Generated by Django 4.1.2 on 2022-11-03 04:09

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0050_alter_treecomboboxmodel_parent_treetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名称')),
                ('desc', simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '表格复选框',
                'verbose_name_plural': '表格复选框',
            },
        ),
    ]
