# Generated by Django 5.0 on 2024-03-31 09:52

import django.db.models.deletion
import simplepro.components.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名字')),
                ('code', simplepro.components.fields.CharField(max_length=32, verbose_name='行政区编码')),
                ('parent', simplepro.components.fields.TreeComboboxField(blank=True, help_text='树形下拉框，选择父级', null=True, on_delete=django.db.models.deletion.CASCADE, to='three_cascade.area', verbose_name='父级')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
    ]
