# Generated by Django 5.0 on 2024-03-31 09:54

import simplepro.components.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_cascade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='行政区编码'),
        ),
    ]
