# Generated by Django 5.0 on 2024-03-31 10:00

import django.db.models.deletion
import simplepro.components.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_cascade', '0002_alter_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名字')),
                ('address', simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='详细地址')),
                ('area', simplepro.components.fields.TreeComboboxField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='three_cascade.area', verbose_name='地区')),
            ],
        ),
    ]
