# Generated by Django 3.1 on 2020-08-22 05:26

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_inputnumbermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.SliderField(default=1, help_text='继承自IntegerField', verbose_name='Slider滑块')),
                ('f2', simplepro.components.fields.SliderField(default=1, help_text='继承自IntegerField', verbose_name='Slider滑块')),
                ('f3', simplepro.components.fields.SliderField(default=1, help_text='继承自IntegerField', verbose_name='Slider滑块')),
            ],
            options={
                'verbose_name': 'Slider滑块',
                'verbose_name_plural': 'Slider滑块',
            },
        ),
        migrations.AlterField(
            model_name='switchmodel',
            name='f',
            field=simplepro.components.fields.SwitchField(default=False, help_text='继承自BooleanField', verbose_name='Switch切换'),
        ),
    ]
