# Generated by Django 3.1 on 2020-08-24 06:40

from django.db import migrations, models
import django.utils.timezone
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_ratemodel_f3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', simplepro.components.fields.TimeField(verbose_name='Time时间选择1')),
                ('f2', simplepro.components.fields.TimeField(default=django.utils.timezone.now, verbose_name='Time时间选择2')),
            ],
            options={
                'verbose_name': 'Time时间选择',
                'verbose_name_plural': 'Time时间选择',
            },
        ),
    ]
