# Generated by Django 3.1 on 2020-08-27 04:04

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_auto_20200827_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': '一对多 Select', 'verbose_name_plural': '一对多 Select'},
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='many_to_many',
        ),
        migrations.CreateModel(
            name='ManyToManyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(default='张三', max_length=128, verbose_name='名字')),
                ('many_to_many', simplepro.components.fields.ManyToManyField(blank=True, to='components.StudentManyToManyModel', verbose_name='多对多字段')),
            ],
            options={
                'verbose_name': '多对多 Select',
                'verbose_name_plural': '多对多 Select',
            },
        ),
    ]
