# Generated by Django 3.1 on 2020-08-27 04:08

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_auto_20200827_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', simplepro.components.fields.IntegerField(choices=[(0, '北大'), (1, '清华'), (2, '复旦'), (3, '交大'), (4, '厦大'), (5, '深大'), (6, '中山大学'), (7, '东南大学'), (8, '南开大学')], default=0, help_text='带下拉框的int字段', verbose_name='学校')),
                ('score', simplepro.components.fields.IntegerField(default=100, help_text='普通int字段', verbose_name='分数')),
            ],
            options={
                'verbose_name': 'Integer字段',
                'verbose_name_plural': 'Integer字段',
            },
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='school',
        ),
    ]
