# Generated by Django 3.1 on 2020-12-02 07:51

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_auto_20200827_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名字')),
            ],
            options={
                'verbose_name': 'Layer Action弹出框',
                'verbose_name_plural': 'Layer Action弹出框',
            },
        ),
    ]
