# Generated by Django 3.2.6 on 2021-08-18 12:54

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0037_alter_checkboxmodeltest_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('geo', models.CharField(blank=True, max_length=32, null=True, verbose_name='经纬度')),
            ],
            options={
                'verbose_name': '高德地图组件',
                'verbose_name_plural': '高德地图组件',
            },
        ),
    ]
