# Generated by Django 3.2.6 on 2021-08-19 03:24

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0038_amapmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='amapmodel',
            name='address',
            field=simplepro.components.fields.AMapField(blank=True, help_text='点击地图获取地址', max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='amapmodel',
            name='geo',
            field=simplepro.components.fields.AMapField(blank=True, help_text='点击地图获取经纬度', max_length=32, null=True, verbose_name='经纬度'),
        ),
    ]
