# Generated by Django 4.0.2 on 2022-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0043_layer_desc_layer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='status',
            field=models.IntegerField(choices=[(0, '默认'), (1, '其他')], default=0, verbose_name='状态'),
        ),
    ]
