# Generated by Django 4.1.1 on 2022-10-19 15:01

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0047_cellactionmodel_treecomboboxmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecomboboxmodel',
            name='name',
            field=simplepro.components.fields.CharField(default=123, max_length=32, verbose_name='名字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treecomboboxmodel',
            name='parent',
            field=simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.treecomboboxmodel', verbose_name='父级'),
        ),
    ]
