# Generated by Django 4.1.2 on 2022-10-27 04:02

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0048_treecomboboxmodel_name_treecomboboxmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomboboxmodel',
            name='parent',
            field=simplepro.components.fields.TreeComboboxField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.treecomboboxmodel', verbose_name='父级'),
        ),
    ]
