# Generated by Django 4.1.2 on 2022-11-02 07:14

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0049_alter_treecomboboxmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecomboboxmodel',
            name='parent',
            field=simplepro.components.fields.TreeComboboxField(blank=True, help_text='树形下拉框，选择父级', null=True, on_delete=django.db.models.deletion.CASCADE, to='components.treecomboboxmodel', verbose_name='父级'),
        ),
        migrations.CreateModel(
            name='TreeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', simplepro.components.fields.CharField(max_length=32, verbose_name='名称')),
                ('desc', simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
                ('parent', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.treetable', verbose_name='父级')),
            ],
            options={
                'verbose_name': '树形表格',
                'verbose_name_plural': '树形表格',
            },
        ),
    ]
