# Generated by Django 2.2 on 2019-09-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工管理'},
        ),
    ]
