# Generated by Django 3.0 on 2019-12-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20191027_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': 'demo1',
                'verbose_name_plural': 'demo1',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='demo2',
            fields=[
                ('demo1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.demo1')),
            ],
            options={
                'verbose_name': 'demo2',
                'verbose_name_plural': 'demo2',
                'ordering': ('name',),
            },
            bases=('demo.demo1',),
        ),
    ]
