# Generated by Django 3.1 on 2020-08-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20200826_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='images',
        ),
    ]
