# Generated by Django 3.1 on 2020-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_manytomanytestmodel_scoremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manytomanytestmodel',
            name='score',
            field=models.ManyToManyField(blank=True, to='demo.ScoreModel', verbose_name='分数'),
        ),
    ]
